#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail # trace ERR through pipes
set -o errtrace # trace ERR through 'time command' and other functions

#set -x

BASEDIR=$(dirname ${BASH_SOURCE})
[ "$BASEDIR" == "." ] || cd $BASEDIR

function copy_files() 
{
	local FROM="$1"
	local TO="$2"

	echo "# Copying files in $FROM to $TO ..."

	while read -r FILENAME
	do
		BASENAME=$(basename $FILENAME)
		DIRNAME=$(dirname $FILENAME)
		PACKAGE=${DIRNAME#$FROM}
		PACKAGE=${PACKAGE#/}

		if grep "${FILENAME}" 'upgrade/excluded'
		then
			echo "Skipped ${FILENAME}"
			rm -f "${TO}/${PACKAGE}/${BASENAME}"
			break
		fi

		[ -d "${TO}/${PACKAGE}" ] || install -d "${TO}/${PACKAGE}"
		if cmp --silent "${FILENAME}" "${TO}/${PACKAGE}/${BASENAME}"
		then
			: # Files are identical. Do nothing.
		else
			if diff --ignore-space-change "${FILENAME}" "${TO}/${PACKAGE}/${BASENAME}"
			then
				: # Files are effectively identical. Do nothing.
			else
				echo "install -p \"${FILENAME}\" \"${TO}/${PACKAGE}\""
				install -p -C "${FILENAME}" "${TO}/${PACKAGE}"
			fi
		fi

		# http://grails.github.io/grails-doc/3.1.x/guide/upgrading.html#upgradingApps
		# Step 4 - Modify Package Imports
		sed -i '' -f 'upgrade/grails_package.sed' "${TO}/${PACKAGE}/${BASENAME}"


		if cmp --silent "${FILENAME}" "${TO}/${PACKAGE}/${BASENAME}"
		then
			# sed 가 모든 파일의 수정시각을 갱신한다. 원본 파일의 시각으로 다시 되돌린다.
			touch -f -m -a -r "${FILENAME}" "${TO}/${PACKAGE}/${BASENAME}"
		else
			# --ignore-space-change suppresses 'No newline at end of file'.
			diff --ignore-space-change "${FILENAME}" "${TO}/${PACKAGE}/${BASENAME}" || :
		fi
	done < <( find $FROM -name *.groovy )
}

cd ..
#copy_files 'common/grails-app/assets' 'common3/grails-app/assets'
#copy_files 'common/grails-app/conf' 'common3/grails-app/conf'
copy_files 'common/grails-app/controllers' 'common3/grails-app/controllers'
copy_files 'common/grails-app/domain' 'common3/grails-app/domain'
#copy_files 'common/grails-app/i18n' 'common3/grails-app/i18n'
copy_files 'common/grails-app/services' 'common3/grails-app/services'
copy_files 'common/grails-app/taglib' 'common3/grails-app/taglib'
copy_files 'common/grails-app/utils' 'common3/grails-app/utils'
copy_files 'common/grails-app/views' 'common3/grails-app/views'
copy_files 'common/src/groovy' 'common3/src/main/groovy'
copy_files 'common/test/integration' 'common3/src/integration-test/groovy'


# vim: set ts=4 noexpandtab :
